# Site settings
title: Yoonsang Yu
email: yooon1104@gmail.com
description: "Last Modified on May 15th 2014<br>Enjoy music if you want!"
baseurl: ""
url: "http://yys1694.com"

# Build settings
markdown: kramdown
permalink: pretty
