# Site settings
title: Yoonsang Yu
email: yooon1104@gmail.com
description: "Last Modified on May 13th 2014<br>Implemented with Jekyll"
baseurl: "http://yys1694.com"
url: "http://yys1694.com"

# Build settings
markdown: kramdown
permalink: pretty
